mysite/urls.py
"""
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
]
"""
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('webapp/', include('webapp.urls')),
    path('admin/', admin.site.urls),
]
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

"""
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webapp.urls', namespace="webapp")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
"""

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls', namespace="webapp")),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

webapp/urls.py
"""Web_App URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = 'webapp'

"""
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^home$', views.home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
"""
urlpatterns = [
    path('', views.index, name='index'),
    path('stadions/', views.stadions, name='stadions'),
    path('faq/', views.faq, name='faq'),
    path('cennik/', views.cennik, name='cennik'),
    path('objednavka/', views.objednavka, name='objednavka'),
    path('kontakt/', views.kontakt, name='kontakt')
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

webapp/models.py
from django.db import models

# Create your models here.

webapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
"""
def index(request):
    return HttpResponse("Hello, world. You're at the webapp index")
"""
"""
def home(request):
    return render(request, 'Web_App/home.html')
"""

# Create views here:
def index(request):
    context = {"home_page": "active"}
    return render(request, 'Web_App/index.html', context)

def stadions (request):
    context = {"stadions_page": "active"}
    return render(request, 'Web_App/stadions.html', context)
def faq (request):
    context = {"faq_page": "active"}
    return render(request, 'Web_App/faq.html', context)

def cennik (request):
    context = {"cennik_page": "active"}
    return render(request, 'Web_App/cennik.html', context)

def objednavka (request):
    context = {"objednavka_page": "active"}
    return render(request, 'Web_App/objednavka.html', context)

def kontakt (request):
    context = {"kontakt_page": "active"}
    return render(request, 'Web_App/kontakt.html', context)
    

webapp/templates/Web_App/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
     <!-- Required meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <!-- Bootstrap 4 css-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" media="all" type="text/css" href="{% static 'Web_App/style.css' %}" />

    <!-- JQuery
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script> -->

    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Courgette&display=swap" rel="stylesheet">

    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    <!-- Font Awesome PRO kit-->
    <script src="https://kit.fontawesome.com/f7db178faf.js"></script>

<title>Piruetka</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}{% endblock %}

<hr class="featurette-divider">

  <!-- FOOTER -->
<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; 2019 Piruetka - Škola korčuľovania &middot; <a href="#">Kódex správania</a> &middot; <a href="#">Ochranna osobných údajov</a></p>
</footer>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    -->
</body>
</html>

webapp/templates/Web_App/faq.html
{% extends "base.html" %}
{% block content %}
<div class="container">
        <h1 class="text-center pt-4 pb-3">Často kladené otázky</h1>
        <div class="text-center">
        <p class="text-center w-75 m-auto font-weight-light">Ak ste tu nenašli odpoveď na svoje otázky, neváhajte nás kontaktovať osobne, telefonicky či mmailom. Radi Vám odpovieme.</p>
        </div>
</div><!--.End container-->


<div class="container">
        <div id="accordion" class="accordion">
            <div class="card mb-0">
                <div class="card-header bg-dark text-white mb-1 rounded collapsed" data-toggle="collapse" href="#collapseOne">
                    <a class="card-title">
                        V akom veku môžem prihlásiť svoje dieťa/seba na korčuľovanie?
                    </a>
                </div>
                <div id="collapseOne" class="card-body collapse" data-parent="#accordion" >
                    <p>My odporúčame na základe našich skúseností a rady ortopédov prihlasovať deti od 4 rokov. Nakoľko do toho veku sa deťom vyvíjajú nožičky.
                        Taktiež zvážte či Vaše dieťa zvládne byť s trénerom samé hodinu.</br>
                        Dospelí nadšenci korčuľovania sa môžú prihlásiť v akomkoľvek veku, podľa svojho uváženia.
                    </p>
                </div>
                <div class="card-header bg-dark text-white mb-1 collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                    <a class="card-title">
                        Ak som ešte nikdy nestál(a) na ľade môžem prísť?
                    </a>
                </div>
                <div id="collapseTwo" class="card-body collapse" data-parent="#accordion" >
                    <p>Samozrejme, naše kurzy sú určené pre všetkých či úplných začiatočníkov, ktorí ešte nikdy nestáli na ľade, až po pokročilých korčuliarov. 
                        Tréner Vás všetko naučí krok po kroku, od úplných začiatkov až po zložité krasokorčuliarske prvky.
                    </p>
                </div>
                <div class="card-header bg-dark text-white mb-1 collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseNine">
                    <a class="card-title">
                        Ako sa zapísať na kurz?
                    </a>
                </div>
                <div id="collapseNine" class="card-body collapse" data-parent="#accordion" >
                    <ol>
                        <li>Vyplňte záväznú prihlášku <a href=""></a></li>
                        <li>V čas uhradte poplatok na náš účet.</li>
                        <li>Na hodinu prídite min. o 15 minút skôr.</li>
                        <li>Prineste si nabrúsené korčule, helmu a dobrú náladu.</li>
                    </ol>
                </div>                
                <div class="card-header bg-dark text-white mb-1 collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                    <a class="card-title">
                            Čo si mám na ľad obliecť?
                    </a>
                </div>
                <div id="collapseThree" class="card-body collapse" data-parent="#accordion" >
                    <p>Na štadiónoch býva väčšinou chladnejšie, niekde až zima. Záleží od konkrétneho ročného obdobia. 
                        V halách býva od jedného stupňa v zime, po 15 na jar. Odporúčame si dať na seba termo oblečenie, šál, čiapku, rukavice (pre deti tvrdené).
                        Menším detičkám odporúčame oteplovačky, keďže sa veľa váľajú po ľade. Všetky deti musia mať <span class="font-weight-bold">lyžiarsku helmu</span>.
                        Cyklistická helma <span class="font-weight-bold">nie je vhodná</span>.
                    </p>
                </div>
                <div class="card-header bg-dark text-white mb-1 collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
                    <a class="card-title">
                        Môžem si u Vás zapožičať korčule?
                    </a>
                </div>
                <div id="collapseFour" class="card-body collapse" data-parent="#accordion" >
                    <p>Áno. Na všetkých štadiónoch kde ponúkame naše kurzy je požičovňa korčúľ , kde sa dajú požičať korčule za malý poplatok.
                    </p>
                </div>
                <div class="card-header bg-dark text-white mb-1 collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
                    <a class="card-title">
                        Musím si kúpiť celý kurz, alebo je možný aj jednorazový vstup?
                    </a>
                </div>
                <div id="collapseFive" class="card-body collapse" data-parent="#accordion" >
                    <p>U nás je samozrejme možnosť si zakúpiť aj jednorazový vstup na konkrétnu hodinu, ak nemáme zaplnené kapacity (platí pre kurzy v Petržalke).
                    </p>
                </div>
                <div class="card-header bg-dark text-white mb-1 collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
                    <a class="card-title">
                        Aké korčule sú najvhodnejšie na kurzy?
                    </a>
                </div>
                <div id="collapseSix" class="card-body collapse" data-parent="#accordion" >
                    <p>Pre deti odporúčame od začiatku korčule na <span class="font-weight-bold">zaväzovanie tzv. šnurovacie</span>. Nie je nutné hneď kupovať nové, stačí ak zakúpite v bazári aj korčule 
                        už nosené, nakoľko deťom rýchlo rastú nohy. Plastové tzv. posuvné korčule neodporúčame. Dieťa sa na týchto korčuliach nedokáže ani zďaleka 
                        naučiť toľko prvkov ako na klasických šnurovacích.
                    </p>
                </div>
                <div class="card-header bg-dark text-white mb-1 collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven">
                        <a class="card-title">
                            Sú nové korčule už nabrúsené?
                        </a>
                    </div>
                    <div id="collapseSeven" class="card-body collapse" data-parent="#accordion" >
                        <p>Nie, nové korčule predávajú štandardne nenabrúsené, preto treba po zakúpení dať korčule hneď nabrúsiť. Korčule brúsia na každom štadióne v Bratislave aj v Pezinku.
                        </p>
                    </div>                                 
            </div>
        </div>
    </div>
{% endblock %}

webapp/templates/Web_App/index.html
{% extends "base.html" %}

{% block content %}
<!-- About us section-->
    <div class="jumbotron jumbotron-fluid bg-white text-center">
        <div class="container">
          <h1 class="display-4">Piruetka - škola korčuľovania</h1>
          <p class="lead">Občianské združenie Piruetka</p>
          {% load static %}
          <img src="{% static "Web_App/images/black_logo.jpg" %}" class="mx-auto d-block img-fluid unlock-icon" alt="Unlock">
        </div>
    </div><!-- /.jumbotron -->

    <div  class="container text-center">
        <h2>Ako sme vznikli</h2>
        <p class="text-center">Za vznikom Piruetky ako Školy korčuľovania stáli dve mladé slečny, ktoré sa začali venovať 
            tomuto športu nie od ranného detstva ako je to zvykom, ale na korčule sa postavili v podstate až v dospelom veku. 
            Tým by chceli poukázať na to, že vek nie je žiadnou prekážkou, keď má niekto záujem, chuť a odhodlanie, môže si splniť 
            svoj sen hocikedy. Našou úlohou je nie len deti, ale aj dospelých motivovať k lepším výkonom, ukázať im aký je tento 
            šport jedinečný a krásny. Našim cieľom je, aby ľudia ktorí k nám prídu, zažívali príjemné pocity a zažili veľa radostných 
            chvíľ na ľade. Samozrejme, že tento šport nie je len o zábave ale aj o drine. </p></br>
        <h2 class="text-center">Čo Vám môžeme ponúknuť</h2>
    </div><!-- /.container -->


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

        <!-- Three columns of text below the carousel -->
    <div class="row">
        <div class="card-group">
                <div class="card border-light">
                    {% load static %}
                    <img src="{% static "Web_App/images/inline_skate.jpg" %}" class="rounded mx-auto" alt="My image">                   
 
                  <div class="card-body text-justify">
                    <h2 class="card-title">In-line korčuľovanie</h5>
                    <p class="card-text">Chcete športovať na vzduchu? Zlepšiť si kondíciu a vytvarovať postavu? Skúste inline korčuľovanie. Spálite toľko 
                            kalórií ako pri behu a navyše si nezaťažíte kĺby. Skvelý spôsob rozhýbať si telo, najmä ak máte sedavé zamestnanie.
                            Korčuľovanie patrí medzi rekreačné športy, ktorý nemá vekové obmedzenie. Jediným obmedzením je sezónnosť a vplyv počasia.</p>
                  </div>
                  <div class="card-footer text-right border-light bg-transparent">
                    <small class="text-muted"><a class="btn btn-primary" href="#" role="button">Objednať &raquo;</a></small>
                  </div>
                </div>
                <div class="card border-light">
                        {% load static %}
                        <img src="{% static "Web_App/images/figure-skate.jpg" %}" class="rounded mx-auto" alt="My image">
                  <div class="card-body text-justify">
                    <h2 class="card-title">Krasokorčuľovanie</h5>
                    <p class="card-text">Krasokorčuľovanie nie je iba šport, ale je to stret pohybu, zákonov fyziky, ladnosti a krásy. Krasokorčušovanie 
                            je jeden z mála športov, ktorý prispieva k utužovaniu imunitného systému. 
                            Korčuľovaním sa podporuje správne držanie tela, koordinácia, rozvoj sily a pohyblivosti. Baví Vás pohyb a tanec? Máte zmysel pre rytmus? 
                            Radi korčuľujete? Stante sa aj Vy krasokorčuliarkou, krasokorčuliarom.</p>
                  </div>
                  <div class="card-footer text-right border-light bg-transparent">
                    <small class="text-muted"><a class="btn btn-primary" href="#" role="button">Objednať &raquo;</a></small>
                  </div>
                </div>
                <div class="card border-light">
                    {% load static %}
                    <img src="{% static "Web_App/images/ice_hockey.jpg" %}" class="rounded mx-auto" alt="My image">                                        
                  <div class="card-body text-justify">
                    <h2 class="card-title">Hokejové korčuľovanie</h5>
                    <p class="card-text">Korčuľovanie je základnou a zároveň najzložitejšou činnosťou hráča ľadového hokeja. Správna technika korčuľovania vytvára
                        dobrý základ pre všetky ostatné hokejové zručnosti - vedenie puku, kľučkovanie, bránenie... Nácvik jednotlivých hokejových zručností 
                        realizuje s profesiónálnymi trénermi. Ak sa chcete zlepšiť či poriadne zapotiť neváhajte sa prihlásiť.
                    </p>
                  </div>
                  <div class="card-footer text-right border-light bg-transparent">
                    <small class="text-muted"><a class="btn btn-primary" href="#" role="button">Objednať &raquo;</a></small>
                  </div>
                </div>
              </div>
    </div><!-- /.row -->
</div><!-- /.container -->

<!--
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <div class="container">
            <ul>
                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
            </ul>
        </div>
-->        



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS 
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    -->
{% endblock %}    

webapp/templates/Web_App/kontakt.html
{% extends "base.html" %}
{% block content %}

<section id="contact">
        <div class="container">
            <h1 class="text-center pt-4 pb-3">Naše kontaktné údaje</h1>
            <p class="text-center w-75 m-auto">Nenašli ste, čo ste hľadali, alebo potrebujete poradiť? Neváhajte sa na nás obrátiť telfonicky alebo emailom. 
                Radi Vám odpovieme a poradíme. Tešíme sa Vás. </p>
            <div class="row">
              <div class="col-sm-12 col-md-6 col-lg-4 my-5">
                <div class="card border-0">
                   <div class="card-body text-center">
                     <i class="fa fa-phone fa-5x mb-3" aria-hidden="true"></i>
                     <h5 class="text-uppercase mb-5">Zavolajte</h5>
                     <h4 class="font-weight-bold">+421 902 443 898</h4>
                   </div>
                 </div>
              </div>
              <div class="col-sm-12 col-md-6 col-lg-4 my-5">
                <div class="card border-0">
                    {% load static %}
                    <img class="img-fluid mx-auto d-block pt-4" src="{% static "Web_App/images/black_logo.jpg" %}" alt="logo">
                 </div>
              </div>
              <div class="col-sm-12 col-md-6 col-lg-4 my-5">
                <div class="card border-0">
                   <div class="card-body text-center">
                     <i class="fa fa-globe fa-5x mb-3" aria-hidden="true"></i>
                     <h5 class="text-uppercase mb-5">email</h5>
                     <h4 class="font-weight-bold">info@piruetka.sk</h4>
                   </div>
                 </div>
              </div>
            </div>
        </div>
     </section>

<div class="container socialmedia">
    <div class="d-flex justify-content-center">
    <ul class="pl-0">
        <li><a href="https://www.facebook.com/klzisko/" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
        <!-- <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li> -->
        <!-- <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li> -->
        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
    </ul>
    </div>
</div>
   
{% endblock %}

webapp/templates/Web_App/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top primary-color">
                <a class="navbar-brand" href="#">Piruetka</a>
                <button class="btn btn-sm align-middle btn-light text-dark font-weight-bold ml-auto mr-3 order-lg-last" type="button">+421 902 443 898</button>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item {{ home_page }}">
                            <a class="nav-link" href="{% url 'webapp:index' %}">Piruetka <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item {{ stadions_page }}">
                            <a class="nav-link" href="{% url 'webapp:stadions' %}">Štadióny</a>
                        </li>
                        <li class="nav-item {{ faq_page }}">
                            <a class="nav-link" href="{% url 'webapp:faq' %}">FAQ</a>
                        </li>                       
                        <li class="nav-item {{ cennik_page }}">
                            <a class="nav-link" href="{% url 'webapp:cennik' %}">Cenník</a>
                        </li>
                        <li class="nav-item {{ objednavka_page }}">
                            <a class="nav-link" href="{% url 'webapp:objednavka' %}">Objednávka</a>
                        </li>
                        <li class="nav-item {{ kontakt_page }}">
                            <a class="nav-link" href="{% url 'webapp:kontakt' %}">Kontakt</a>
                        </li>
                    </ul>
                </div>
        </nav>
 

webapp/templates/Web_App/objednavka.html
{% extends "base.html" %}
{% block content %}
<h1>Hello from the objednavka page</h1>
{% endblock %}